set(_CATKIN_CURRENT_PACKAGE "pcl_msgs")
set(pcl_msgs_VERSION "0.3.0")
set(pcl_msgs_MAINTAINER "Paul Bovbel <paul@bovbel.com>, Bill Morris <bill@neautomation.com>")
set(pcl_msgs_PACKAGE_FORMAT "1")
set(pcl_msgs_BUILD_DEPENDS "message_generation" "sensor_msgs" "std_msgs")
set(pcl_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "sensor_msgs" "std_msgs")
set(pcl_msgs_BUILDTOOL_DEPENDS "catkin")
set(pcl_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_msgs_EXEC_DEPENDS "message_runtime" "sensor_msgs" "std_msgs")
set(pcl_msgs_RUN_DEPENDS "message_runtime" "sensor_msgs" "std_msgs")
set(pcl_msgs_TEST_DEPENDS )
set(pcl_msgs_DOC_DEPENDS )
set(pcl_msgs_URL_WEBSITE "http://wiki.ros.org/pcl_msgs")
set(pcl_msgs_URL_BUGTRACKER "https://github.com/ros-perception/pcl_msgs/issues")
set(pcl_msgs_URL_REPOSITORY "https://github.com/ros-perception/pcl_msgs")
set(pcl_msgs_DEPRECATED "")